package com.is.client.laptopservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-05-10T23:48:37.747+02:00
 * Generated source version: 3.4.5
 *
 */
@WebServiceClient(name = "LaptopServiceImplService",
                  wsdlLocation = "http://localhost:8080/services/LaptopService?wsdl",
                  targetNamespace = "http://web.is.com/")
public class LaptopServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.is.com/", "LaptopServiceImplService");
    public final static QName LaptopServiceImplPort = new QName("http://web.is.com/", "LaptopServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/services/LaptopService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LaptopServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/services/LaptopService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LaptopServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LaptopServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LaptopServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LaptopServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LaptopServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LaptopServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LaptopService
     */
    @WebEndpoint(name = "LaptopServiceImplPort")
    public LaptopService getLaptopServiceImplPort() {
        return super.getPort(LaptopServiceImplPort, LaptopService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LaptopService
     */
    @WebEndpoint(name = "LaptopServiceImplPort")
    public LaptopService getLaptopServiceImplPort(WebServiceFeature... features) {
        return super.getPort(LaptopServiceImplPort, LaptopService.class, features);
    }

}
