package com.is.client.laptopservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-05-10T23:48:37.741+02:00
 * Generated source version: 3.4.5
 */
@WebService(targetNamespace = "http://web.is.com/", name = "LaptopService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface LaptopService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://web.is.com/", partName = "return")
    public int customMethod(

            @WebParam(partName = "arg0", name = "arg0")
            int arg0,
            @WebParam(partName = "arg1", name = "arg1")
            int arg1
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://web.is.com/", partName = "return")
    public int getNumberOfRecordsByProducer(

            @WebParam(partName = "arg0", name = "arg0")
            String arg0
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://web.is.com/", partName = "return")
    public XmlInputFormatArray getRecordsByScreenType(

            @WebParam(partName = "arg0", name = "arg0")
            String arg0
    );

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://web.is.com/", partName = "return")
    public StringArray getAllDistinctScreenTypes()
            ;

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://web.is.com/", partName = "return")
    public StringArray getAllDistinctProducers()
            ;
}
